### ISSUE TITLE
cd command not working

### ISSUE THREAD

**Issue by mks9467** [ojroques/python-sshcontroller#1]
Hi I am trying to cd into a folder and it just doesn't do anything

**Comment by ojroques** [comment]
Hello!

If you want to execute a command in a particular remote directory, you have to `cd` into it and run that command in one go. For instance this should work:
```sh
ssh_controller.run("cd my-folder && <your command>")
```

But this won't:
```sh
ssh_controller.run("cd my-folder")
ssh_controller.run("<your command>")
```

This is because each time you call `run()` a new SSH channel is created and you are being placed into the remote `home` directory.

**Comment by mks9467** [comment]
Ok great thanks
